import { Pencil, Plus, Target, WalletCards } from 'lucide-react';
import { useState } from 'react';
import { Button, Modal, Money, PageHeader, Pill, ProgressBar, SectionLabel } from '@/components/finance-ui';
import { useFinance } from '@/domain/store';
import type { Budget } from '@/domain/finance';

export default function Budgets() {
  const { budgets, categories, transactions, saveBudget } = useFinance();
  const [editing, setEditing] = useState<Budget | null>(null);
  const [creating, setCreating] = useState(false);
  const getSpent = (categoryId: string) => transactions.filter((txn) => txn.categoryId === categoryId && txn.kind === 'purchase').reduce((sum, txn) => sum + txn.amount, 0);
  return <div data-testid="page-budgets"><PageHeader eyebrow="A little structure" title="Budgets" description="Set limits that describe your real month. Going over is information, not a verdict." action={<Button onClick={() => setCreating(true)} testId="button-add-budget"><Plus className="h-4 w-4" />Add a limit</Button>} />
    <div className="mb-8 flex items-center gap-4 border border-border bg-card p-5"><div className="flex h-11 w-11 items-center justify-center bg-[hsl(43_92%_69%/.3)] text-[hsl(35_55%_29%)]"><Target className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold">March 2025 limits</p><p className="mt-1 text-xs text-muted-foreground">Rollover is undecided for now. These limits only describe this month.</p></div><span className="hidden font-mono-finance text-xs text-muted-foreground sm:block">{budgets.length} categories</span></div>
    <SectionLabel>Category limits</SectionLabel><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{budgets.map((budget) => { const category = categories.find((cat) => cat.id === budget.categoryId); const spent = getSpent(budget.categoryId); const ratio = spent / budget.limit; return <div key={budget.id} className={`border bg-card p-5 ${ratio > 1 ? 'border-destructive/40' : 'border-border'}`} data-testid={`card-budget-${budget.id}`}><div className="flex items-start justify-between"><div className="flex items-center gap-3"><span className="h-3 w-3" style={{ backgroundColor: category?.color }} /><div><h3 className="text-sm font-semibold">{category?.name}</h3><p className="mt-1 text-xs text-muted-foreground">{category?.description}</p></div></div><button type="button" onClick={() => setEditing(budget)} className="focus-ring p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label={`Edit ${category?.name} budget`} data-testid={`button-edit-budget-${budget.id}`}><Pencil className="h-4 w-4" /></button></div><div className="mt-8 flex items-baseline justify-between"><span className="font-display text-3xl"><Money value={spent} /></span><span className="font-mono-finance text-xs text-muted-foreground">of <Money value={budget.limit} /></span></div><div className="mt-3"><ProgressBar value={ratio * 100} tone={ratio > 1 ? 'red' : ratio > .8 ? 'yellow' : 'teal'} /></div><div className="mt-3 flex justify-between text-xs">{ratio > 1 ? <Pill tone="red">Over by <Money value={spent - budget.limit} /></Pill> : <span className="text-muted-foreground"><Money value={budget.limit - spent} /> left</span>}<span className="text-muted-foreground">{Math.round(ratio * 100)}%</span></div></div> })}<button type="button" onClick={() => setCreating(true)} className="focus-ring flex min-h-[220px] flex-col items-center justify-center border border-dashed border-border bg-transparent p-5 text-center text-muted-foreground transition hover:border-primary hover:bg-primary/5" data-testid="button-add-budget-card"><span className="mb-3 flex h-10 w-10 items-center justify-center border border-border"><Plus className="h-5 w-5" /></span><span className="text-sm font-semibold">Add another limit</span><span className="mt-1 text-xs">Keep it useful, not exhaustive</span></button></div>
    <div className="mt-10 grid gap-5 md:grid-cols-2"><div className="border border-border bg-[hsl(181_48%_34%/.07)] p-6"><WalletCards className="mb-5 h-5 w-5 text-primary" /><h3 className="font-display text-2xl">A good limit is a question.</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">“Do I want to spend more than $300 on food this month?” is more useful than a perfect forecast.</p></div><div className="border border-border bg-card p-6"><p className="font-mono-finance text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Month in numbers</p><p className="mt-5 font-display text-3xl"><Money value={budgets.reduce((sum, item) => sum + item.limit, 0)} /></p><p className="mt-1 text-sm text-muted-foreground">total planned limits</p><div className="mt-5 flex gap-6 text-sm"><span><strong className="block text-foreground">{budgets.filter((item) => getSpent(item.categoryId) > item.limit).length}</strong><span className="text-xs text-muted-foreground">over limit</span></span><span><strong className="block text-foreground">{budgets.filter((item) => getSpent(item.categoryId) / item.limit > .8 && getSpent(item.categoryId) <= item.limit).length}</strong><span className="text-xs text-muted-foreground">nearly there</span></span></div></div></div>
    {(editing || creating) && <BudgetModal budget={editing} categories={categories.filter((category) => !category.system)} onClose={() => { setEditing(null); setCreating(false); }} onSave={(data) => { saveBudget(data); setEditing(null); setCreating(false); }} />}
  </div>;
}

function BudgetModal({ budget, categories, onClose, onSave }: { budget: Budget | null; categories: ReturnType<typeof useFinance>['categories']; onClose: () => void; onSave: (budget: Omit<Budget, 'id'> & { id?: string }) => void }) {
  const [categoryId, setCategoryId] = useState(budget?.categoryId ?? categories[0]?.id ?? '');
  const [limit, setLimit] = useState(String(budget?.limit ?? ''));
  return <Modal title={budget ? 'Edit category limit' : 'Create a category limit'} description="This applies to March 2025 only. Rollover behavior is still undecided." onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); onSave({ ...(budget?.id ? { id: budget.id } : {}), categoryId, month: '2025-03', limit: Number(limit) }); }}><label className="mb-2 block text-sm font-semibold" htmlFor="budget-category">Category</label><select id="budget-category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="focus-ring mb-5 h-11 w-full border border-border bg-card px-3 text-sm" data-testid="select-budget-category">{categories.map((cat) => <option key={cat.id} value={cat.id}>{cat.name}</option>)}</select><label className="mb-2 block text-sm font-semibold" htmlFor="budget-limit">Monthly limit</label><div className="relative mb-7"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span><input id="budget-limit" type="number" min="1" step="1" value={limit} onChange={(event) => setLimit(event.target.value)} className="focus-ring h-11 w-full border border-border bg-card pl-8 pr-3 font-mono-finance text-sm outline-none" placeholder="300" required data-testid="input-budget-limit" /></div><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose} testId="button-cancel-budget">Cancel</Button><Button type="submit" testId="button-save-budget">Save limit</Button></div></form></Modal>;
}