import { Check, Info, Pencil, Plus, Power, Tag, WandSparkles } from 'lucide-react';
import { useState } from 'react';
import { Button, Modal, PageHeader, Pill, SectionLabel } from '@/components/finance-ui';
import { useFinance } from '@/domain/store';
import type { Category, CategoryRule } from '@/domain/finance';

export default function Categories() {
  const { categories, rules, saveCategory, saveRule, toggleRule } = useFinance();
  const [editingCategory, setEditingCategory] = useState<Category | null>(null);
  const [editingRule, setEditingRule] = useState<CategoryRule | null>(null);
  const [newRule, setNewRule] = useState(false);
  return <div data-testid="page-categories"><PageHeader eyebrow="Your vocabulary" title="Categories" description="A small set of words that make your spending legible. Rules help; your corrections always win." action={<Button onClick={() => setEditingCategory({ id: '', name: '', color: '#4e8f89', description: '' })} testId="button-add-category"><Plus className="h-4 w-4" />New category</Button>} />
    <div className="grid gap-10 xl:grid-cols-[.9fr_1.1fr]"><section><SectionLabel action={<span className="text-xs text-muted-foreground">{categories.filter((cat) => !cat.system).length} custom</span>}>Spending categories</SectionLabel><div className="divide-y divide-border border border-border bg-card">{categories.filter((cat) => !cat.system).map((category) => <div key={category.id} className="flex items-center gap-4 px-5 py-4" data-testid={`row-category-${category.id}`}><span className="h-3 w-3" style={{ backgroundColor: category.color }} /><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{category.name}</p><p className="mt-1 truncate text-xs text-muted-foreground">{category.description}</p></div><button type="button" onClick={() => setEditingCategory(category)} className="focus-ring p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label={`Edit ${category.name}`} data-testid={`button-edit-category-${category.id}`}><Pencil className="h-4 w-4" /></button></div>)}</div><div className="mt-4 flex gap-3 border border-dashed border-border p-4 text-xs leading-5 text-muted-foreground"><Info className="h-4 w-4 shrink-0 text-primary" />Income and Uncategorized are built in. Transfers stay outside spending totals.</div></section>
      <section><SectionLabel action={<Button variant="secondary" onClick={() => setNewRule(true)} testId="button-add-rule"><Plus className="h-4 w-4" />Add rule</Button>}>Categorization rules</SectionLabel><div className="mb-4 flex gap-3 border border-border bg-[hsl(181_48%_34%/.07)] p-4 text-sm leading-6"><WandSparkles className="mt-1 h-4 w-4 shrink-0 text-primary" /><span>Rules suggest a category automatically. A manual correction is always kept as a correction and is never overwritten.</span></div><div className="divide-y divide-border border border-border bg-card">{rules.map((rule) => <div key={rule.id} className={`px-5 py-4 ${!rule.enabled ? 'opacity-55' : ''}`} data-testid={`row-rule-${rule.id}`}><div className="flex items-start gap-3"><span className="mt-0.5 flex h-8 w-8 items-center justify-center bg-muted"><Tag className="h-4 w-4 text-primary" /></span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">“{rule.merchantPattern}” <span className="font-normal text-muted-foreground">→</span> {categories.find((cat) => cat.id === rule.categoryId)?.name}</p><p className="mt-1 text-xs text-muted-foreground">{rule.matches} matching transactions · updated {rule.updatedAt}</p></div><div className="flex items-center gap-1"><button type="button" onClick={() => toggleRule(rule.id)} className="focus-ring p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label={`${rule.enabled ? 'Disable' : 'Enable'} rule for ${rule.merchantPattern}`} data-testid={`button-toggle-rule-${rule.id}`}>{rule.enabled ? <Power className="h-4 w-4 text-primary" /> : <Power className="h-4 w-4" />}</button><button type="button" onClick={() => setEditingRule(rule)} className="focus-ring p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label={`Edit rule for ${rule.merchantPattern}`} data-testid={`button-edit-rule-${rule.id}`}><Pencil className="h-4 w-4" /></button></div></div>{!rule.enabled && <div className="mt-2 pl-11"><Pill>Disabled · no new assignments</Pill></div>}</div>)}</div></section></div>
    {editingCategory && <CategoryModal category={editingCategory} onClose={() => setEditingCategory(null)} onSave={(data) => { saveCategory(data); setEditingCategory(null); }} />}
    {(editingRule || newRule) && <RuleModal rule={editingRule} categories={categories.filter((cat) => !cat.system)} onClose={() => { setEditingRule(null); setNewRule(false); }} onSave={(data) => { saveRule(data); setEditingRule(null); setNewRule(false); }} />}
  </div>;
}

function CategoryModal({ category, onClose, onSave }: { category: Category; onClose: () => void; onSave: (category: Omit<Category, 'id'> & { id?: string }) => void }) {
  const [name, setName] = useState(category.name);
  const [description, setDescription] = useState(category.description);
  const [color, setColor] = useState(category.color);
  return <Modal title={category.id ? 'Edit category' : 'New category'} description="Use a name you will recognize when reviewing a busy month." onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); onSave({ ...(category.id ? { id: category.id } : {}), name, description, color }); }}><label className="mb-2 block text-sm font-semibold" htmlFor="category-name">Name</label><input id="category-name" value={name} onChange={(event) => setName(event.target.value)} className="focus-ring mb-5 h-11 w-full border border-border bg-card px-3 text-sm outline-none" placeholder="Learning" required data-testid="input-category-name" /><label className="mb-2 block text-sm font-semibold" htmlFor="category-description">Description</label><input id="category-description" value={description} onChange={(event) => setDescription(event.target.value)} className="focus-ring mb-5 h-11 w-full border border-border bg-card px-3 text-sm outline-none" placeholder="Courses, books, and new skills" data-testid="input-category-description" /><label className="mb-2 block text-sm font-semibold" htmlFor="category-color">Accent color</label><input id="category-color" type="color" value={color} onChange={(event) => setColor(event.target.value)} className="mb-7 h-11 w-full border border-border bg-card p-1" data-testid="input-category-color" /><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose} testId="button-cancel-category">Cancel</Button><Button type="submit" testId="button-save-category"><Check className="h-4 w-4" />Save category</Button></div></form></Modal>;
}

function RuleModal({ rule, categories, onClose, onSave }: { rule: CategoryRule | null; categories: Category[]; onClose: () => void; onSave: (rule: Omit<CategoryRule, 'id'> & { id?: string }) => void }) {
  const [merchantPattern, setMerchantPattern] = useState(rule?.merchantPattern ?? '');
  const [categoryId, setCategoryId] = useState(rule?.categoryId ?? categories[0]?.id ?? '');
  return <Modal title={rule ? 'Edit rule' : 'New categorization rule'} description="Match part of a merchant name. You can disable this later without losing your history." onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); onSave({ ...(rule?.id ? { id: rule.id } : {}), merchantPattern, categoryId, enabled: rule?.enabled ?? true, matches: rule?.matches ?? 0, updatedAt: 'Today' }); }}><label className="mb-2 block text-sm font-semibold" htmlFor="rule-pattern">When merchant contains</label><input id="rule-pattern" value={merchantPattern} onChange={(event) => setMerchantPattern(event.target.value)} className="focus-ring mb-5 h-11 w-full border border-border bg-card px-3 text-sm outline-none" placeholder="e.g. Juniper" required data-testid="input-rule-pattern" /><label className="mb-2 block text-sm font-semibold" htmlFor="rule-category">Assign to</label><select id="rule-category" value={categoryId} onChange={(event) => setCategoryId(event.target.value)} className="focus-ring mb-7 h-11 w-full border border-border bg-card px-3 text-sm" data-testid="select-rule-category">{categories.map((cat) => <option key={cat.id} value={cat.id}>{cat.name}</option>)}</select><div className="flex justify-end gap-2"><Button variant="secondary" onClick={onClose} testId="button-cancel-rule">Cancel</Button><Button type="submit" testId="button-save-rule"><Check className="h-4 w-4" />Save rule</Button></div></form></Modal>;
}