import { AlertTriangle, CheckCircle2, ChevronDown, FileText, Info, Upload } from 'lucide-react';
import { useState } from 'react';
import { Button, EmptyState, PageHeader, Pill, SectionLabel } from '@/components/finance-ui';
import { accounts, useFinance } from '@/domain/store';

export default function Imports() {
  const { imports } = useFinance();
  const [expanded, setExpanded] = useState<string | null>(imports[0]?.id ?? null);
  const [loading, setLoading] = useState(false);
  const inspect = () => { setLoading(true); setTimeout(() => setLoading(false), 600); };
  return <div data-testid="page-imports"><PageHeader eyebrow="Bring it in gently" title="Imports" description="CSV review is intentionally explicit here. Nothing gets silently added to your story." action={<Button onClick={inspect} disabled={loading} testId="button-start-import"><Upload className="h-4 w-4" />{loading ? 'Preparing…' : 'Start an import'}</Button>} />
    <div className="mb-8 grid gap-4 md:grid-cols-3"><div className="border border-border bg-card p-5"><p className="font-mono-finance text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Batches this month</p><p className="mt-5 font-display text-3xl">{imports.length}</p><p className="mt-1 text-xs text-muted-foreground">one needs your review</p></div><div className="border border-border bg-card p-5"><p className="font-mono-finance text-[10px] uppercase tracking-[0.14em] text-muted-foreground">Rows inspected</p><p className="mt-5 font-display text-3xl">48</p><p className="mt-1 text-xs text-muted-foreground">date formats understood</p></div><div className="border border-border bg-[hsl(43_92%_69%/.22)] p-5"><p className="font-mono-finance text-[10px] uppercase tracking-[0.14em] text-[hsl(35_55%_29%)]">Needs attention</p><p className="mt-5 font-display text-3xl">2</p><p className="mt-1 text-xs text-[hsl(35_55%_29%)]">rows held back for review</p></div></div>
    <SectionLabel>Import history</SectionLabel><div className="border border-border bg-card">{imports.length === 0 ? <EmptyState title="No imports yet" description="Your next reviewed CSV will show up here." icon={<FileText className="h-6 w-6" />} /> : imports.map((batch) => <div key={batch.id} className="border-b border-border last:border-0" data-testid={`card-import-${batch.id}`}><button type="button" onClick={() => setExpanded(expanded === batch.id ? null : batch.id)} className="focus-ring flex w-full items-center gap-4 px-5 py-5 text-left hover:bg-muted/40"><span className="flex h-10 w-10 items-center justify-center bg-muted"><FileText className="h-5 w-5 text-primary" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{batch.fileName}</span><span className="mt-1 block text-xs text-muted-foreground">{accounts.find((account) => account.id === batch.accountId)?.name} · {batch.importedAt}</span></span><span className="hidden items-center gap-4 sm:flex"><span className="text-right"><span className="block font-mono-finance text-sm">{batch.added}/{batch.rows}</span><span className="block text-[11px] text-muted-foreground">rows added</span></span><Pill tone={batch.status === 'review' ? 'yellow' : 'teal'}>{batch.status === 'review' ? 'Review' : 'Complete'}</Pill></span><ChevronDown className={`h-4 w-4 text-muted-foreground transition ${expanded === batch.id ? 'rotate-180' : ''}`} /></button>{expanded === batch.id && <div className="border-t border-border bg-muted/20 px-5 py-5 sm:pl-[84px]"><div className="mb-4 grid gap-3 sm:grid-cols-2">{batch.warnings.map((warning) => <div key={warning.id} className={`flex gap-3 border p-4 ${warning.severity === 'attention' ? 'border-[hsl(43_78%_57%/.4)] bg-[hsl(43_92%_69%/.15)]' : 'border-border bg-card'}`} data-testid={`warning-${warning.id}`}>{warning.severity === 'attention' ? <AlertTriangle className="h-4 w-4 shrink-0 text-[hsl(35_55%_29%)]" /> : <Info className="h-4 w-4 shrink-0 text-primary" />}<span><strong className="block text-sm">{warning.message}</strong><span className="mt-1 block text-xs leading-5 text-muted-foreground">{warning.detail}</span></span></div>)}</div><div className="flex flex-wrap items-center gap-3"><Button variant="secondary" testId={`button-review-import-${batch.id}`}>Review held rows</Button><span className="flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5 text-primary" />No rows added without review</span></div></div>}</div>)}</div>
    <div className="mt-8 border border-dashed border-border p-5 text-sm leading-6 text-muted-foreground"><strong className="text-foreground">This is a prototype.</strong> File selection and CSV parsing are not connected yet. The review model above is real local state and is designed for a future import service.</div>
  </div>;
}