import { ArrowDownLeft, ArrowUpRight, ChevronLeft, ChevronRight, CircleAlert, Sparkles } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Button, Money, Pill, ProgressBar, SectionLabel } from '@/components/finance-ui';
import { accounts, useFinance } from '@/domain/store';
import { Link } from 'wouter';

export default function Overview() {
  const { transactions, budgets, categories } = useFinance();
  const [month, setMonth] = useState('March 2025');
  const spending = transactions.filter((item) => item.kind === 'purchase' && item.categoryId !== 'cat-income').reduce((sum, item) => sum + item.amount, 0);
  const income = transactions.filter((item) => item.categoryId === 'cat-income').reduce((sum, item) => sum + item.amount, 0);
  const uncategorized = transactions.filter((item) => item.source === 'uncategorized').length;
  const budgetTotal = budgets.reduce((sum, item) => sum + item.limit, 0);
  const budgetSpent = budgets.reduce((sum, budget) => sum + transactions.filter((txn) => txn.categoryId === budget.categoryId && txn.kind === 'purchase').reduce((total, txn) => total + txn.amount, 0), 0);
  const topCategories = useMemo(() => budgets.map((budget) => ({ ...budget, category: categories.find((cat) => cat.id === budget.categoryId), spent: transactions.filter((txn) => txn.categoryId === budget.categoryId && txn.kind === 'purchase').reduce((sum, txn) => sum + txn.amount, 0) })).sort((a, b) => b.spent - a.spent).slice(0, 4), [budgets, categories, transactions]);
  const recent = transactions.filter((txn) => txn.kind !== 'transfer').slice(0, 5);
  return <div data-testid="page-overview">
    <div className="mb-8 flex flex-col gap-5 border-b border-border pb-7 sm:flex-row sm:items-end sm:justify-between">
      <div><p className="mb-2 font-mono-finance text-[11px] uppercase tracking-[0.18em] text-primary">A quieter look at money</p><h1 className="font-display text-4xl tracking-[-0.04em] text-foreground sm:text-5xl">Good morning, Alex.</h1><p className="mt-2 text-sm text-muted-foreground">Here’s the shape of March so far. Nothing needs to be perfect.</p></div>
      <div className="flex items-center gap-2 self-start sm:self-auto"><button type="button" className="focus-ring flex h-10 w-10 items-center justify-center border border-border bg-card hover:bg-muted" onClick={() => setMonth('February 2025')} aria-label="Previous month" data-testid="button-previous-month"><ChevronLeft className="h-4 w-4" /></button><button type="button" className="focus-ring flex h-10 items-center gap-3 border border-border bg-card px-4 text-sm font-semibold hover:bg-muted" onClick={() => setMonth(month === 'March 2025' ? 'April 2025' : 'March 2025')} data-testid="button-month-selector">{month}<ChevronDownIcon /></button><button type="button" className="focus-ring flex h-10 w-10 items-center justify-center border border-border bg-card hover:bg-muted" onClick={() => setMonth('April 2025')} aria-label="Next month" data-testid="button-next-month"><ChevronRight className="h-4 w-4" /></button></div>
    </div>
    <div className="grid gap-4 md:grid-cols-3">
      <div className="bg-primary p-6 text-primary-foreground"><div className="flex items-start justify-between"><p className="font-mono-finance text-[10px] uppercase tracking-[0.15em] text-primary-foreground/70">Out this month</p><ArrowUpRight className="h-4 w-4 text-accent" /></div><p className="mt-7 font-display text-4xl"><Money value={spending} /></p><p className="mt-2 text-sm text-primary-foreground/70">Across {transactions.filter((item) => item.kind === 'purchase').length} purchases</p></div>
      <div className="border border-border bg-card p-6"><div className="flex items-start justify-between"><p className="font-mono-finance text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Coming in</p><ArrowDownLeft className="h-4 w-4 text-primary" /></div><p className="mt-7 font-display text-4xl text-foreground"><Money value={income} /></p><p className="mt-2 text-sm text-muted-foreground">Brightside Payroll · Mar 16</p></div>
      <div className="border border-border bg-[hsl(43_92%_69%/.22)] p-6"><div className="flex items-start justify-between"><p className="font-mono-finance text-[10px] uppercase tracking-[0.15em] text-[hsl(35_55%_29%)]">Still to notice</p><CircleAlert className="h-4 w-4 text-[hsl(35_55%_29%)]" /></div><p className="mt-7 font-display text-4xl text-foreground">{uncategorized}<span className="ml-2 text-xl text-muted-foreground">transactions</span></p><p className="mt-2 text-sm text-[hsl(35_55%_29%)]">A small five-minute tidy-up</p></div>
    </div>
    <div className="mt-8 grid gap-8 xl:grid-cols-[1.35fr_.65fr]">
      <section><SectionLabel action={<Link href="/budgets" className="focus-ring text-xs font-semibold text-primary hover:underline" data-testid="link-view-budgets">See budgets <ArrowUpRight className="ml-1 inline h-3 w-3" /></Link>}>March pulse</SectionLabel><div className="border border-border bg-card p-6"><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-muted-foreground">Planned spending</p><p className="mt-1 font-display text-3xl"><Money value={budgetSpent} /><span className="ml-2 text-base text-muted-foreground">of <Money value={budgetTotal} /></span></p></div><Pill tone={budgetSpent > budgetTotal ? 'red' : 'teal'}>{Math.round((budgetSpent / budgetTotal) * 100)}% used</Pill></div><ProgressBar value={(budgetSpent / budgetTotal) * 100} tone={budgetSpent > budgetTotal ? 'red' : 'teal'} /><div className="mt-7 grid gap-5 sm:grid-cols-2">{topCategories.map(({ category, spent, limit }) => <div key={category?.id} data-testid={`budget-pulse-${category?.id}`}><div className="mb-2 flex items-center justify-between text-sm"><span className="flex items-center gap-2"><span className="h-2 w-2" style={{ backgroundColor: category?.color }} />{category?.name}</span><span className="font-mono-finance text-xs text-muted-foreground"><Money value={spent} /> / <Money value={limit} /></span></div><ProgressBar value={(spent / limit) * 100} tone={spent > limit ? 'red' : spent / limit > .8 ? 'yellow' : 'teal'} /></div>)}</div></div></section>
      <section><SectionLabel action={<Link href="/transactions" className="focus-ring text-xs font-semibold text-primary hover:underline" data-testid="link-view-transactions">All activity <ArrowUpRight className="ml-1 inline h-3 w-3" /></Link>}>Recent activity</SectionLabel><div className="divide-y divide-border border border-border bg-card">{recent.map((txn) => <Link href="/transactions" key={txn.id} data-testid={`row-recent-${txn.id}`} className="flex items-center gap-3 px-4 py-4 transition hover:bg-muted/60"><span className="flex h-9 w-9 items-center justify-center bg-muted text-sm font-semibold" style={{ color: categories.find((cat) => cat.id === txn.categoryId)?.color }}>{txn.merchant.slice(0, 1)}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{txn.merchant}</span><span className="block text-xs text-muted-foreground">{new Date(txn.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span></span><span className={`font-mono-finance text-sm ${txn.kind === 'refund' ? 'text-primary' : ''}`}><Money value={txn.amount} signed /></span></Link>)}</div></section>
    </div>
    <section className="mt-8"><SectionLabel>Accounts at a glance</SectionLabel><div className="grid gap-3 md:grid-cols-3">{accounts.map((account) => <div key={account.id} className="flex items-center justify-between border border-border bg-card px-5 py-4" data-testid={`account-card-${account.id}`}><div className="flex items-center gap-3"><span className="h-3 w-3" style={{ backgroundColor: account.color }} /><div><p className="text-sm font-semibold">{account.name}</p><p className="text-xs text-muted-foreground">{account.institution} · ···{account.lastFour}</p></div></div><span className={`font-mono-finance text-sm ${account.balance < 0 ? 'text-destructive' : ''}`}><Money value={account.balance} /></span></div>)}</div></section>
    <div className="mt-8 flex items-center gap-3 border border-dashed border-primary/35 bg-primary/5 p-4 text-sm text-primary"><Sparkles className="h-4 w-4 shrink-0" /><span><strong>A useful next step:</strong> review the 2 uncategorized transactions before setting April’s limits.</span><Link href="/transactions" className="ml-auto shrink-0 font-semibold underline" data-testid="link-review-uncategorized">Review</Link></div>
  </div>;
}

function ChevronDownIcon() {
  return <svg aria-hidden="true" viewBox="0 0 16 16" className="h-4 w-4 text-muted-foreground"><path d="m4 6 4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.5" /></svg>;
}