import { Check, ChevronDown, Moon, ShieldCheck, Sun, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Button, PageHeader, SectionLabel } from '@/components/finance-ui';

export default function Settings() {
  const [saved, setSaved] = useState(false);
  const [currency, setCurrency] = useState('USD');
  const [weekStart, setWeekStart] = useState('Monday');
  const [compact, setCompact] = useState(false);
  const save = () => { setSaved(true); setTimeout(() => setSaved(false), 1400); };
  return <div data-testid="page-settings"><PageHeader eyebrow="Make it yours" title="Settings" description="A few choices about how Tallywell speaks to you. Nothing here changes your transactions." action={<Button onClick={save} testId="button-save-settings">{saved ? <><Check className="h-4 w-4" />Saved</> : 'Save preferences'}</Button>} />
    <div className="grid gap-10 xl:grid-cols-[1.15fr_.85fr]"><section><SectionLabel>Personal preferences</SectionLabel><div className="border border-border bg-card"><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Currency</p><p className="mt-1 text-xs text-muted-foreground">Used across amounts and limits.</p></div><select value={currency} onChange={(event) => setCurrency(event.target.value)} className="focus-ring h-10 border border-border bg-card px-3 text-sm sm:w-36" data-testid="select-currency"><option>USD</option><option>CAD</option><option>EUR</option><option>GBP</option></select></div><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold">Week starts on</p><p className="mt-1 text-xs text-muted-foreground">Used for weekly summaries only.</p></div><select value={weekStart} onChange={(event) => setWeekStart(event.target.value)} className="focus-ring h-10 border border-border bg-card px-3 text-sm sm:w-36" data-testid="select-week-start"><option>Monday</option><option>Sunday</option></select></div><div className="flex items-center justify-between p-5"><div><p className="text-sm font-semibold">Compact transaction rows</p><p className="mt-1 text-xs text-muted-foreground">Show more of your month at once.</p></div><button type="button" onClick={() => setCompact(!compact)} className={`focus-ring relative h-6 w-11 shrink-0 transition ${compact ? 'bg-primary' : 'bg-muted'}`} role="switch" aria-checked={compact} data-testid="switch-compact-rows"><span className={`absolute top-1 h-4 w-4 bg-card transition-transform ${compact ? 'translate-x-6' : 'translate-x-1'}`} /></button></div></div>
      <SectionLabel>Display</SectionLabel><div className="border border-border bg-card"><button type="button" className="focus-ring flex w-full items-center gap-4 border-b border-border p-5 text-left hover:bg-muted/40" data-testid="button-theme-setting"><span className="flex h-9 w-9 items-center justify-center bg-[hsl(43_92%_69%/.25)]"><Sun className="h-4 w-4 text-[hsl(35_55%_29%)]" /></span><span className="flex-1"><span className="block text-sm font-semibold">Light, warm</span><span className="mt-1 block text-xs text-muted-foreground">A calm paper-like canvas for clarity.</span></span><ChevronDown className="h-4 w-4 text-muted-foreground" /></button><div className="flex items-center gap-4 p-5"><span className="flex h-9 w-9 items-center justify-center bg-muted"><Moon className="h-4 w-4 text-muted-foreground" /></span><div><p className="text-sm font-semibold text-muted-foreground">Dark mode</p><p className="mt-1 text-xs text-muted-foreground">Not available in this prototype.</p></div></div></div></section>
      <aside><SectionLabel>Account display</SectionLabel><div className="border border-border bg-card p-6"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center bg-primary font-display text-xl text-primary-foreground">AM</span><div><p className="font-display text-2xl">Alex Morgan</p><p className="mt-1 text-sm text-muted-foreground">alex.morgan@example.com</p></div></div><div className="mt-7 space-y-4 border-t border-border pt-5"><div className="flex items-center gap-3 text-sm"><UserRound className="h-4 w-4 text-primary" />Personal space</div><div className="flex items-center gap-3 text-sm"><ShieldCheck className="h-4 w-4 text-primary" />Local prototype data</div></div></div><div className="mt-4 border border-border bg-[hsl(181_48%_34%/.07)] p-5"><p className="font-mono-finance text-[10px] uppercase tracking-[0.14em] text-primary">A note on privacy</p><p className="mt-3 text-sm leading-6 text-muted-foreground">This prototype keeps sample data in your browser session. No banks are connected, and no account credentials are stored.</p></div></aside></div>
  </div>;
}